apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-course-cluster
  region: ap-southeast-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh: # use existing EC2 key
      publicKeyName: eks-course
  - name: scale-ap-southeast-1a
    instanceType: t2.small
    desiredCapacity: 1
    maxSize: 10
    availabilityZones: ["ap-southeast-1a"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateful-workload
      instance-type: onDemand
    ssh: # use existing EC2 key
      publicKeyName: eks-course